/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_jni_test_Tester */

#ifndef _Included_fi_jni_test_Tester
#define _Included_fi_jni_test_Tester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_jni_test_Tester
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fi_jni_test_Tester_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
